error id: wE+GNE1RJJbZ0ItTQF5eIQ==
### Bloop error:

at scala.Main$.scala$Main$$anon$3$$_$_$$anonfun$1(Main.scala:51)
#### Short summary: 

at scala.Main$.scala$Main$$anon$3$$_$_$$anonfun$1(Main.scala:51)